{application,storm_collector,
             [{description,[]},
              {vsn,"1"},
              {modules,[parser,storm_collector_app,storm_collector_server,
                        storm_collector_storage,storm_collector_sup]},
              {registered,[]},
              {applications,[kernel,stdlib,hackney]},
              {mod,{storm_collector_app,[]}},
              {env,[]}]}.
